### ISSUE TITLE
Pre-generation of signature caches

### ISSUE THREAD

**Issue by boesing** [CuyZ/Valinor#115]
Hey there,

I recently started to use this library.
I was thinking of actually writing a CLI command for CI pipeline which searches for the `TreeMapper#map` usage and parses the 1st argument (FQCN) from it.

I do want to pass this FQCN to the `TypeParser#parse` method so that the `cacheDirectory` entry is being created.

What I found out is, that there is no way to actually get an instance of the `TypeParser` and I do really would love to avoid instantiating it by myself.

Do you have an idea and/or suggestion on how to retrieve the `TypeParser` instance with the settings I do pass to the `MapperBuilder`?

Would love to get some help here so we can pre-generate the cache entries on the filesystem during build-time.

Thanks in advance 🤙🏼

**Comment by romm** [comment]
Hi @boesing, I did not give access to the container instance on purpose to avoid giving access to everything (which would result in more maintenance burden).

However, this is a good suggestion, and a part of this feature could even be part of the public API provided by the library, maybe something like `MapperBuilder::warmup(SomeClass::class, SomeOtherClass::class)`. I'd be happy to help/review if you were to add this to the core of the library. 🙂

**Comment by romm** [comment]
Closed with #116.
