### ISSUE TITLE
Detect unused properties by allowing ArrayAccess as source

### ISSUE THREAD

**Issue by eigan** [CuyZ/Valinor#148]
I want to detect if a property in source is sent but never ends up being used (for instance a typo). By allowing Source to be ArrayAccess could this be trivial to implement outside of Valinor _(register used properties in `MySource::offsetGet`)_. I made some very small adjustments to Valinor to make it work (for my very basic DTO), but would need some more testing. 

What do you think of the idea?

![2022-06-08-200548_334x195_scrot](https://user-images.githubusercontent.com/41789/172686469-0e22f585-d3ed-4100-83c2-ffbe245059ba.png)

**Comment by romm** [comment]
Hi @eigan, I'm currently working on a stricter version of the mapper, which will be able to detect unused keys; I'll keep you updated here so you can give feedback when it's ready to be tested. 🙂

**Comment by romm** [comment]
Hi @eigan, #159 should solve this issue. Could you take a look and give feedback? 🙂

**Comment by eigan** [comment]
```php
<?php

require "vendor/autoload.php";

use CuyZ\Valinor\Mapper\MappingError;
use CuyZ\Valinor\Mapper\Tree\Node;

final class Foo
{
    public string $note;
    public ?string $bar = null;
}

try {
    (new \CuyZ\Valinor\MapperBuilder())
        ->mapper()
        ->map(Foo::class, [
            'bar' => 12,
            'foo' => 'Hello world'
        ]);
} catch (MappingError $e) {
    print_node($e->node());
}

function print_node(Node $node): void
{
    foreach ($node->messages() as $message) {
        echo $node->path() . ": " .$message . "\n";
    }

    foreach ($node->children() as $child) {
        print_node($child);
    }
}

```

## Result
```
note: Cannot be empty and must be filled with a value matching type `string`.
bar: Value 12 does not match type `string`.
```

## Expected
```diff
  note: Cannot be empty and must be filled with a value matching type `string`.
  bar: Value 12 does not match type `string`.
+ Unexpected key(s) `foo`, expected `note`, `bar`.
```
Might not be a bug, just a bit more convenient to show all messages at once 🙂

**Comment by romm** [comment]
Good suggestion, I just updated the PR. That also helped me to spot a bug, so thank you. 😄
