### ISSUE TITLE
Separate exceptions for field missing and cast fail

### ISSUE THREAD

**Issue by mstosicfb** [CuyZ/Valinor#158]
Is there a way to differentiate if the field is missing from the input array from the case when it exists, but it can't be cast?
If I'm not missing something, both use cases throw CannotCastToScalarValue exception.

It would be handy if those were separate exceptions.

**Comment by romm** [comment]
Hi @mstosicfb you will be very happy to know that I'm currently working on a stricter mode of the mapper which should solve this issue.

I'll keep you updated here to let you know when it's ready, and I'd be very happy to have your feedback when it's available for being tested!

**Comment by romm** [comment]
Hi @mstosicfb, #159 brings a separation between those cases you described. Could you take a look, try it on your side and give feedback?

**Comment by mstosicfb** [comment]
Hi @romm, thanks for the quick response, and quicker prototype solution.

I've tested changes from https://github.com/CuyZ/Valinor/pull/159, exceptions now work like expected, but the catch is that it only works with strict mode. Flexible mode still returns the same CannotCastToScalarValue exception in both cases. 
Is this behaviour intentional?

By the way, I like the idea of strict mode, and will probably consider transitioning to it, but it's not currently possible since I get mixed data from some sources. Is the strict mode going to be the main focus in the future development?

**Comment by romm** [comment]
Hi @mstosicfb, you're absolutely right and the behavior has been changed. Could you try again and check if it's ok by your side?

The strict mode is the new default of the mapper, as described in the [new chapter of the documentation](https://github.com/CuyZ/Valinor/blob/15feb62eacd9eacfabecb54357a2cdb171935ee4/docs/pages/mapping/type-strictness.md#type-strictness). I'm not sure to understand what you mean by "main focus in the future development"?
