### ISSUE TITLE
How can I add the path to a Message

### ISSUE THREAD

**Issue by DavideBicego** [CuyZ/Valinor#166]
I'd like to add the subject of the issue so that catching the MappingError I can compose an API response similar to
```json
{
    "issues": [
        {
            "subject": "my_subject",
            "message": "Want is wrong with the subject"
        }
    ]
}

```

I'm throwing a custom Exception like this one in the mapping signature Object constructor
```php
use CuyZ\Valinor\Mapper\Tree\Message\Message;

use function implode;
use function sprintf;

class InvalidEnumValue extends \DomainException implements Message
{
    /**
     * @param list<Enum> $enumValues
     */
    public static function forEnum(array $enumValues, string $value): self
    {
        return new self(sprintf('Value \'%s\' is not valid, valid values are %s', $value, '\''
            . implode('\', \'', $enumValues) . '\''));
    }
}
```

Do you have any suggestion?

By the way the reason why I need to throw a custom exception here is because the mapper isn't able to map a string to an `\MyCLabs\Enum\Enum`. The issue seems to be the current Psalm annotations inside `\MyCLabs\Enum\Enum`.
Are Psalm annotations used in some way to map the object?

**Comment by DavideBicego** [comment]
> when working with messages (as described in [the documentation](https://valinor.cuyz.io/latest/message-customization/)) you can get all messages data like `$message->path()`; that should help you.

But only for those Message objects generated by the library, I can't find a way to initialize my custom Exception that implements Message with a path defined. Am I missing something?

**Comment by DavideBicego** [comment]
> Concerning the enums, I think that the generic templates are not working because of the inheritance (which is a missing feature of this lib, unfortunately). Good news is, you should be able to use a [custom constructor](https://valinor.cuyz.io/latest/mapping/construction-strategy/#custom-constructor) in the meantime (maybe that's already what you do?).

I tried with
```php
(new MapperBuilder())
    ->registerConstructor(
        [MyEnum::class, 'from'],
    )
    ->mapper();
```
but I receive a `CuyZ\Valinor\Type\Types\UnresolvableType`.

I tried with
```php
(new MapperBuilder())
    ->registerConstructor(
        function (string $value): Status
        {
            return Status::from($value);
        },
    )
    ->mapper();
```

but i receive a `CuyZ\Valinor\Definition\Exception\InvalidPropertyDefaultValue`
```
Message: Default value of property `MyCLabs\Enum\Enum::$instances` is not accepted by `array>`.
...
```
which is exactly the same error that occurs if I don't specify any custom construct

**Comment by DavideBicego** [comment]
The exact same code gives me a CuyZ\Valinor\Definition\Exception\InvalidPropertyDefaultValue:
```
Default value of property `MyCLabs\Enum\Enum::$instances` is not accepted by `array<string, array<string, ...MyNamespace\SomeEnum>>``
```

I'm using
- cuyz/valinor 0.11.0
- myclabs/php-enum 1.8.3
- psalm 4.23.0

**Comment by romm** [comment]
Hi @DavideBicego could you try checking out #172 and see if that solves this issue for you?

**Comment by DavideBicego** [comment]
Unfortunately I tried but with
```php
(new MapperBuilder())
    ->registerConstructor(
        [MyEnum::class, 'from'],
    )
    ->mapper();
```
I still get a CuyZ\Valinor\Type\Types\UnresolvableType with message: The type `static` for return type of method `MyCLabs\Enum\Enum::from()` could not be resolved: No generic was assigned to the template(s) `T` for the class `MyCLabs\Enum\Enum`.

And With
```php
(new MapperBuilder())
    ->registerConstructor(
        function (string $value): Status
        {
            return Status::from($value);
        },
    )
    ->mapper();
```
I still get a  CuyZ\Valinor\Definition\Exception\InvalidPropertyDefaultValue with message: Default value of property `MyCLabs\Enum\Enum::$instances` is not accepted by `array<string, array<string, Namespace/To/MyEnum>>`.

**Comment by romm** [comment]
Hi @DavideBicego something must be wrong with the second option, because the exception `InvalidPropertyDefaultValue` was totally removed in the PR. Are you sure you checked the correct branch in your environment?

**Comment by DavideBicego** [comment]
I'm sorry, something must have gone wrong.
This are the actual responses.
With
```php
[MyEnum::class, 'from'],
```
I still get the same response

But With
```php
function (string $value): Status
{
    return Status::from($value);
},
```
It works! 👍 

I also tried with no registered constructor and the response is a `CuyZ\Valinor\Mapper\Tree\Exception\UnresolvableShellType` with message: The type `T` for parameter `MyCLabs\Enum\Enum::__construct($value)` could not be resolved: Cannot parse unknown symbol `T`.

**Comment by romm** [comment]
Yeah unfortunately I wont be able to fix this issue for now. Glad it works in your project!

Closing the issue.
