### ISSUE TITLE
Having two infer do not work

### ISSUE THREAD

**Issue by magnetik** [CuyZ/Valinor#169]
Hi,

It seems that having two infer registered do not work.

I've done a "as simple as possible" repro code here : https://github.com/magnetik/valinor-repro

When I register A before B I have an error on B, and when I register B before A, I have an error on A. 

Is there something I'm missing?

**Comment by romm** [comment]
Hi @magnetik, good catch! Thanks for the repo, helped a lot to reproduce the issue locally.

Could you check #170 to see if that fixes your issue?

**Comment by magnetik** [comment]
I just tested and it works (the `Root` class was not correct in my example, but it works when fixed) !

**Comment by romm** [comment]
Perfect, thank you!
