### ISSUE TITLE
Named constructor support would be handy

### ISSUE THREAD

**Issue by brandonsavage** [CuyZ/Valinor#17]
Presently, as designed, this library (which is excellent, BTW) only supports direct instantiation of objects through PHP's constructor method. It would be handy to permit the use of named constructors, that map the specific data to a particular static named constructor. This might be an optional third argument to `TreeMapper::map()`?

**Comment by romm** [comment]
Actually, a lot of things are not documented (yet™) 😅 but that's already a feature (if I understood correctly), see:

https://github.com/CuyZ/Valinor/blob/ea842e2efb94ded9f9f2ebce1484f8d4e7e29237/tests/Integration/Mapping/Attribute/ObjectBuilderStrategyMappingTest.php#L59-L78

For classes that define several named constructors, a custom `ObjectBuilder` could be used I guess, I'd have to take a deeper look.

**Comment by brandonsavage** [comment]
Very nice! Truly beautiful. I'll close this for now and reopen it if I run into problems. Thanks so much!
