### ISSUE TITLE
Example from doc not working with PHPStan

### ISSUE THREAD

**Issue by jamesRUS52** [CuyZ/Valinor#171]
PHPStan return error 
Method MyClass::getResponse() should return MyClass but returns object.    

```php
public static function getResponse(string $rawJson): self
{
        return (new \CuyZ\Valinor\MapperBuilder())
            ->mapper()
            ->map(
                self::class,
                new \CuyZ\Valinor\Mapper\Source\JsonSource($rawJson)
            );
}
```

**Comment by szepeviktor** [comment]
This change _would_ resolve this problem.
https://github.com/CuyZ/Valinor/pull/187/files

**Comment by romm** [comment]
Hi @jamesRUS52, thanks for the report.

I can't reproduce it on my local environment, using PHPStan 1.6.7. What versions of Valinor and PHPStan are you using?

**Comment by eigan** [comment]
@jamesRUS52 Can you reproduce this on phpstan.org?

I was not able to.
https://phpstan.org/r/eb782ea4-5c29-4bd0-a67b-7fe0f7cc2904

**Comment by romm** [comment]
Same here.

Closing this issue, feel free to reopen if the issue persists on your side.

Thanks @eigan for the update. 😉
