### ISSUE TITLE
Proper CI

### ISSUE THREAD

**Issue by szepeviktor** [CuyZ/Valinor#179]
Would you welcome a CI configuration that runs each QA tool in a separate job?

**Comment by romm** [comment]
I think that's not necessary, the CI is mostly here to check that everything is fine. For my local development, I always check before pushing so it happens in rare cases when the CI output is actually useful.

Maybe if/when the contribution workflow needs to be improved, but I'm not sure it will be necessary.

Thanks for asking, though. :)

**Comment by szepeviktor** [comment]
Okay.

When one ✔️ or ❌ belongs to one QA tool contributors may see what tool failed.
