### ISSUE TITLE
Could the mapper be pure?

### ISSUE THREAD

**Issue by Ocramius** [CuyZ/Valinor#192]
Looking at `TreeMapper`, I wonder if we can mark `map()` as `@psalm-pure`, allowing us to force the design of all internal callbacks (specifically userland ones) to not perform I/O or side-effects in general.

This would greatly improve the safety of the mapper, even if it is reduced in scope.

**Comment by romm** [comment]
Sounds like a great idea indeed.

I'm currently using it in a customer's project to fetch entities directly from the DB, but I was already asking myself if I was not abusing the library's capabilities…

I'll take some time to think about it. Also, I'd love to have comments/feedback from other users and contributors on this suggestion; I'll allow myself one ping, hope that's ok with you guys 😅  — @Mopolo @ @Slamdunk @brandonsavage @brayniverse @shulard (others are obviously more than welcome to join the discussion!)

**Comment by brayniverse** [comment]
Hi @romm, I'm not using this library on any active projects at the moment but I appreciate the consideration. I have no objections to `map()` being marked as `@psalm-pure`.

**Comment by romm** [comment]
Hi @Ocramius, after giving it some thoughts I agree on the proposal; I've submitted #260, any chance you can take a look and tell me if something is wrong with my approach?

Cheers. 🙂
