### ISSUE TITLE
CuyZ\Valinor\Definition\Exception\TypesDoNotMatch: Return types for method `Ramsey\Uuid\Uuid::fromBytes()` do not match: `Ramsey\Uuid\Rfc4122\UuidInterface` (docblock) does not accept `Ramsey\Uuid\UuidInterface` (native).

### ISSUE THREAD

**Issue by pscheit** [CuyZ/Valinor#196]
Hi there,

thanks so much for writing valinor. Now i have this error:

```
CuyZ\Valinor\Definition\Exception\TypesDoNotMatch: Return types for method `Ramsey\Uuid\Uuid::fromBytes()` do not match: `Ramsey\Uuid\Rfc4122\UuidInterface` (docblock) does not accept `Ramsey\Uuid\UuidInterface` (native).
```

I tried:
```
        $this->mapper = (new MapperBuilder())
            ->infer(UuidInterface::class, fn() => UuidV4::class)
```

to avoid:
```
CuyZ\Valinor\Mapper\Tree\Exception\ResolvedImplementationIsNotAccepted: Invalid implementation type `Ramsey\Uuid\UuidInterface`, expected a subtype of `Ramsey\Uuid\UuidInterface`.
```

I read thats a problem with the ramsey library. But how can I workaround it? Why does it pick the fromBytes even if I provide a customer constructor?

Thanks for the help, i just updated to v0.13

**Comment by romm** [comment]
Hi @pscheit, sorry for the late answer — I'm coming with good news though.

This issue should be fixed with #273; I'm closing the issue feel free to reopen if you still have a problem after the next release of the library is out.

Thanks for the report!
