### ISSUE TITLE
Best way to map inputs?

### ISSUE THREAD

**Issue by timmipetit** [CuyZ/Valinor#200]
First of all: great library!

We're trying to use this library to map GET request params in our API to some DTO. Some stuff is easy to map, but other stuff a bit more complex. I'm wondering what the best/recommended way is to map stuff around.

For example, our API accepts a `?product_id=1,2,3` request that we want to map to an array of ints. So let's say our constructor looks something like this:
```php
public function __construct(
    /** @var int[] */
    public readonly array $product_id = []
)
```

Should we add a named constructor for this case, or is stuff like this doable with a `->map()` call?

**Comment by romm** [comment]
Hi @timmipetit, using named constructor is completely up to you and your needs; if a native constructor or public readonly property is enough, there is probably no need to declare named constructors.

Not sure if it answers your question though. Have you had troubles using the mapper?

**Comment by timmipetit** [comment]
Thanks for the reply @romm. Didn't try the mapper really, since we couldn't find much documentation about it. We've solved it now by using a named constructor, but we might be able to rewrite it a bit. Was just curious about what is considered to be best practice for this library

**Comment by romm** [comment]
Hi @timmipetit, actually there is documentation at [valinor.cuyz.io](https://valinor.cuyz.io/); have you checked that already?

In any case, I hope your project is going well. 😉
