### ISSUE TITLE
Separate config for ignoring extra fields and allowing casts

### ISSUE THREAD

**Issue by AndrolGenhald** [CuyZ/Valinor#203]
`MapperBuilder::flexible()` enables flexible mode to automatically cast types and ignore extra fields, but I would like to ignore extra fields _without_ casting types. Ignoring unknown JSON fields in a REST API is pretty common to help with forward compatibility, but I'd like to keep the types strict.

**Comment by romm** [comment]
Hi @AndrolGenhald, you are not the first one to ask for a way to distinguish these two options. I'll definitely think about a way to make it possible, I'll keep you updated here.

**Comment by AndrolGenhald** [comment]
I might take a stab at it myself in a week or two. It doesn't seem too difficult, and a quick search shows that most of the relevant classes are `@internal` so compatibility shouldn't be too hard to handle.

**Comment by boesing** [comment]
I would be +1 on this.

We do use use valinor in the exact same scenario: API response to DTO mapping.
Since adding new properties to a response is not a BC break, this shouldn't lead to problems in valinor.

For now, I do actually set `flexible` again but I only have to do that to allow new properties to exist.

**Comment by romm** [comment]
Hi @AndrolGenhald & @boesing, could you take a look at #248 and tell me what you think of it?

**Comment by AndrolGenhald** [comment]
Looks great to me! That's pretty similar to what I had been working on before my day job took all my time away.

**Comment by boesing** [comment]
LGTM as well. Having every feature configurable dedicatedly makes the most sense to me.

**Comment by romm** [comment]
Released with [0.17.0](https://github.com/CuyZ/Valinor/releases/tag/0.17.0).

Enjoy!
