### ISSUE TITLE
Support class const wildcard

### ISSUE THREAD

**Issue by AndrolGenhald** [CuyZ/Valinor#204]
Psalm and PHPStan support using `Foo::Bar_*` as a union type of all class constants in `Foo` matching `Bar_*`: https://psalm.dev/r/1171a1c5c6 https://phpstan.org/r/0dc72c36-508b-43d0-8f10-726b12a4a847

It would be really nice to have this in Valinor so I don't have to go copy all of the literal values into a union type and make sure it stays in sync.

**Comment by romm** [comment]
Hi @AndrolGenhald, closing as duplicate of #119.

Thanks for the submission though, also you'll be glad to hear that I already have a prototype working locally for both constants and enum cases. Some things are missing but this will definitely be available in an upcoming release!
