### ISSUE TITLE
Allow trailing comma in array shapes

### ISSUE THREAD

**Issue by AndrolGenhald** [CuyZ/Valinor#205]
Similar to PHP arrays, argument lists, etc, I like to use trailing commas for multi-line array shapes: https://psalm.dev/r/c2542c6325

When I do this for a constructor param used by Valinor it complains about:

> detail: Wrong token type `CuyZ\Valinor\Type\Parser\Lexer\Token\ClosingCurlyBracketToken`, it should be an instance of `CuyZ\Valinor\Type\Parser\Lexer\Token\TraversingToken`.

**Comment by romm** [comment]
Good catch, I'll submit a fix for it ASAP. 😉
