### ISSUE TITLE
Question: How to map an object to another object?

### ISSUE THREAD

**Issue by boesing** [CuyZ/Valinor#232]
Hey there,

I have a use-case where I do query elasticsearch and already get back a `json_decode`d object.
As far as I see, there is no proper way to actually have non-arrays to be mapped.

Am I missing something or do I have to `json_encode` my objects before I pass them to the mapper to be mapped to my signature?

**Comment by romm** [comment]
Hi @boesing, indeed there is no such feature as deserialization in this library right now, so I guess the best thing to do right now would be something like `json_decode(json_encode($yourObject), true)`.

Maybe one day I'll consider adding this kind of feature, but this is not planned yet.

**Comment by brayniverse** [comment]
In your particular scenario could you cast the JSON decoded object to an array?

```php
$json = '{"foo": "bar", "baz": [1, 2, 3]}';
$decodedJson = json_decode($json, false);

$array = (new MapperBuilder())
    ->mapper()
    ->map(
        'array{foo: string, baz: array<int>}',
        (array) $decodedJson,
    );
```

I guess it depends on the complexity of the object that elasticsearch is providing you but if it's a basic stdClass object this should work (see example https://3v4l.org/TvUEp).

**Comment by romm** [comment]
Hi @boesing, I'll consider this issue as answered.

Feel free to re-open if needed. 😉

**Comment by slepic** [comment]
@romm hello, i have the same issue, i have an object already json_decode'd but it is with assiaciative=false
I am already casting objects to arrays before passing them to mapper, but i finally have case where i have an object with nested objects, i can cast the top level object, but casting recursively all of its properties is tedious and it would really help if this was handled by the mapper.

i probably am going to json_encode and decode assiaciatively again for now, as this is actually in tests and so i dont care for perf
but it actually leaves a gap - a piece of non working code - which is just not used in prod setup (yet?)

so i just wanted to raise my hand for this feature
