### ISSUE TITLE
Support PHP 8.2

### ISSUE THREAD

**Issue by acelaya** [CuyZ/Valinor#233]
Hey!

Is there any plan to support PHP 8.2? I'm using this package in pipelines with PHP 8.2 where I install deps with `--ignore-platform-req=php+`, and everything works fine, so I guess officially supporting it should be relatively straightforward.

I can provide a PR if you are ok with it.

**Comment by acelaya** [comment]
Amazing! Thanks a lot 🙂

**Comment by romm** [comment]
Done, and available with [0.16.0](https://github.com/CuyZ/Valinor/releases/tag/0.16.0). 😉
