### ISSUE TITLE
Multiple cache roundtrips

### ISSUE THREAD

**Issue by marcospassos** [CuyZ/Valinor#241]
The library is currently using the `Cache::has` method that is intended for caching warmup, thus performing many roundtrips. For cache backends that perform IO, this is a huge performance penalty.

From the spec:

>   NOTE: It is recommended that has() is only to be used for cache warming type purposes
     and not to be used within your live applications operations for get/set, as this method
     is subject to a race condition where your has() will return true and immediately after,
     another script can remove it, making the state of your app out of date.

**Comment by romm** [comment]
Thank you @marcospassos!
