### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by nd2021** [CuyZ/Valinor#261]
composer require cuyz/valinor problem:
```
Your requirements could not be resolved to an installable set of packages.
- cuyz/valinor 0.17.0 requires psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
```

Already released psr/simple-cache 3.0.0:
https://packagist.org/packages/psr/simple-cache

**Comment by romm** [comment]
Hi @nd2021, sorry for the inconvenience; the first major release of this library will be published at the beginning of next week, it will update the requirements and allow `psr/simple-cache:^3.0`.

May I ask which PHP version your application is running on?

**Comment by nd2021** [comment]
Great! PHP 8.1

**Comment by romm** [comment]
Hi @nd2021, [version `1.0.0` has been released](https://github.com/CuyZ/Valinor/releases/tag/1.0.0) and should fix your issue.

Closing the issue. 😉
