### ISSUE TITLE
Allowing superfluous keys for array of enums

### ISSUE THREAD

**Issue by uchuu-me** [CuyZ/Valinor#280]
Add something like "Allowing superfluous keys" for array of enums.
Example:
https://github.com/CuyZ/Valinor/commit/7becb60c079aba9f996918abf9b5ef411f759fa4#diff-a48898ae8da7053f43be7593fe3507ffd14c54e207d537c345e1ab21e7d8ab4aR66

**Comment by romm** [comment]
Hi @uchuu-me, I'm having difficulties understanding what is really needed here. Could you provide an example of what you want to achieve?

**Comment by uchuu-me** [comment]
`
enum Color: string
{
    case GREEN = 'GREEN';
    case RED = 'RED';
}

class Toy
{
    public function __construct(
        public string $name,
        /** @var array<Color> */
        public array $colors = []
    ) {
    }
}

$toy = (new MapperBuilder())
    ->allowSuperfluousKeys()
    ->mapper()
    ->map(Toy::class, [
            'name' => 'Teddy',
            'colors' => [
                'GREEN',
                'UNKNOWN' // This should be skipped.
            ]
        ]
    );
`

**Comment by romm** [comment]
I see; however I don't have plans to add such "feature", as this has nothing to do with superfluous keys, but rather invalid values which is exactly what this library is about: detect invalid values and warn the user about it.

What *could* be done is to use a custom constructor for the enum, something like the code below, but at the moment **it does not work**. I'll have to add support for enum constructor, which is clearly a missing feature. I'll keep you updated here when it becomes possible.


```php
enum Color: string
{
    case GREEN = 'GREEN';
    case RED = 'RED';

    public static function createFrom(string $value): self
    {
        return self::tryFrom($value) ?? self::RED;
    }
}

class Toy
{
    public function __construct(
        public string $name,
        /** @var array<Color> */
        public array $colors = []
    ) {}
}

$toy = (new MapperBuilder())
    ->allowSuperfluousKeys()
    ->registerConstructor(Color::createFrom(...))
    ->mapper()
    ->map(Toy::class, [
            'name' => 'Teddy',
            'colors' => [
                'GREEN',
                'UNKNOWN',
            ]
        ]
    );
```

**Comment by eliashaeussler** [comment]
Hi @romm, defining a custom constructor for enums is something I'm also missing. The following code throws an exception because of the missing construction support:

```php
enum ChangeFrequency: string
{
    case Always = 'always';
    case Hourly = 'hourly';
    case Daily = 'daily';
    case Weekly = 'weekly';
    case Monthly = 'monthly';
    case Yearly = 'yearly';
    case Never = 'never';

    public static function fromCaseInsensitive(string $changeFrequency): self
    {
        return self::from(strtolower($changeFrequency));
    }
}

class Url
{
    /**
     * @throws Exception\InvalidUrlException
     */
    public function __construct(
        public readonly string $uri,
        public readonly float $priority = 0.5,
        public readonly ?ChangeFrequency $changeFrequency = null,
    ) {
    }
}

$mapper = (new MapperBuilder())
    ->registerConstructor(
        ChangeFrequency::fromCaseInsensitive(...),
    )
    ->supportDateFormats(DateTimeInterface::W3C)
    ->mapper();

$url = $mapper->map(Url::class, [
    'uri' => 'https://www.example.com',
    'priority' => 1.0,
    // should be accepted due to custom constructor
    'changeFrequency' => 'HOURLY',
]);
```

I get the following error:

```
Value 'HOURLY' does not match any of 'always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never'.
```

**Comment by romm** [comment]
Hi there, I'm closing this issue in favor of #316; I'll keep you updated there when work has been done on this topic.

**Comment by romm** [comment]
@uchuu-me @eliashaeussler version 1.3.0 [has been released](https://github.com/CuyZ/Valinor/releases/tag/1.3.0), with a support for enum constructors. Enjoy!

**Comment by eliashaeussler** [comment]
@romm Wow, that's great news! Thanks for all your work 💛
