### ISSUE TITLE
Mapping error with class with only one property

### ISSUE THREAD

**Issue by JorgeOnrubiaMojica** [CuyZ/Valinor#287]
`(new MapperBuilder())
            ->mapper()
            ->map(TestDTO::class, Source::array(["id" => 1]))`

`final class TestDTO
{
    public function __construct(
        public readonly int $id
    )
    {
    }
}`

Show this error:

CuyZ\Valinor\Mapper\TypeTreeMapperError : Could not map type `*****\TestDTO`. An error occurred at path *root*: Value object(CuyZ\Valinor\Mapper\Source\Source) does not match type `int`.

**Comment by romm** [comment]
Hi @JorgeOnrubiaMojica, this is a duplicate issue of #269, I might work on a solution later, see https://github.com/CuyZ/Valinor/issues/269#issuecomment-1332290737.

**Comment by romm** [comment]
Hi @JorgeOnrubiaMojica, just wanted to let you know that a fix has been merged, see https://github.com/CuyZ/Valinor/issues/269#issuecomment-1374252049

**Comment by JorgeOnrubiaMojica** [comment]
Thank you
