### ISSUE TITLE
Class with single property

### ISSUE THREAD

**Issue by uchuu-me** [CuyZ/Valinor#294]
```php
enum Color: string
{
    case GREEN = 'GREEN';
    case RED = 'RED';
}

class Toy
{
    public function __construct(
        public Color $color
    ) {
    }
}

$toy = (new MapperBuilder())
    ->mapper()
    ->map(Toy::class, [
            'color' => 'RED'
        ]
    );
```
Fatal error: Uncaught CuyZ\Valinor\Mapper\TypeTreeMapperError: Could not map type `Toy`. An error occurred at path *root*: Value array{color: 'RED'} does not match type `GREEN|RED`

Here is the problem place
https://github.com/CuyZ/Valinor/blob/master/src/Mapper/Object/ArgumentsValues.php#L80

**Comment by bronek89** [comment]
I think its related to issue that I've reported: https://github.com/CuyZ/Valinor/issues/269

**Comment by romm** [comment]
> I think its related to issue that I've reported: #269

It is. As stated in https://github.com/CuyZ/Valinor/issues/269#issuecomment-1361273018 I'll probably go for a revert of the change that disabled this feature.

**Comment by romm** [comment]
Hi @uchuu-me, just wanted to let you know that a fix has been merged, see https://github.com/CuyZ/Valinor/issues/269#issuecomment-1374252049
