### ISSUE TITLE
Return types for method do not match: `list<array-key>` (docblock) does not accept `array`

### ISSUE THREAD

**Issue by danog** [CuyZ/Valinor#300]
First of all, I'm absolutely loving how Valinor is turning into a fully-fledged, runtime equivalent of a static analysis tool, now even with method return type checks for mapped classes!

However, I noticed that in one specific instance a certain check is behaving incorrectly:

```php

class a {
    /** @var array<string> */
    public function __construct(private array $a)
    {
    }

	/**
	 * @return list<array-key>
	 */
	public function getPropertiesList(): array {
		return array_keys($this->a);
	}
}

(new MapperBuilder)->mapper()->map(a::class, ['a' => []]);
```

throws "Return types for method `a::getPropertiesList()` do not match: `list<array-key>` (docblock) does not accept `array`"

**Comment by fcoedno** [comment]
@danog have you managed to solve this issue? I've been facing the same one
