### ISSUE TITLE
Confusing InvalidConstructorReturnType message when template isn't specified

### ISSUE THREAD

**Issue by AndrolGenhald** [CuyZ/Valinor#307]
I was trying to use a closure as a custom constructor, and it gave me an `InvalidConstructorReturnType` exception even though its return signature definitely specifies an existing class. When debugging I discovered that it was being thrown [here](https://github.com/CuyZ/Valinor/blob/1577233ac9dce444af61bb482f5a744e38eaf739/src/Mapper/Object/Factory/ConstructorObjectBuilderFactory.php#L97), and `$returnType` was an `UnresolvableType` with the message:

```
"The type `[my type]` for return type of method `[my closure constructor]` could not be resolved: No generic was assigned to the template(s) `T` for the class `[my type]`."
```

It would be great if the `InvalidConstructorReturnType` message could be improved to account for cases where the class does exist but there is a template left unspecified.

**Comment by romm** [comment]
Hi @AndrolGenhald, thanks for the report. The issue has been fixed with #347 and will be part of the next release. 😉
