### ISSUE TITLE
Arbitrary UTF-8 chars in literals are not supported

### ISSUE THREAD

**Issue by danog** [CuyZ/Valinor#309]
```php
<?php

use CuyZ\Valinor\MapperBuilder;

require 'vendor/autoload.php';

/**
 * @psalm-type TCur = array{'$': string}
 */
final class a {

    /**
     * @param TCur $a
     */
    public function __construct(
        public readonly array $a,
    ) {
    }
}

(new MapperBuilder)->mapper()->map(a::class, ['$a' => 'test']);

```

Yields "The type `array{'` for local alias `TCur` of the class `a` could not be resolved: Closing quote is missing for ``."

**Comment by danog** [comment]
Actually it seems like the regex should just allow any characters, to account for non-UTF8 characters like àèìòù in array keys

**Comment by danog** [comment]
Even simple cases like string literals with spaces don't work:
```php
<?php

use CuyZ\Valinor\MapperBuilder;

require 'vendor/autoload.php';

final class a {

    /**
     * @param 'a a' $a
     */
    public function __construct(
        public readonly string $a,
    ) {
    }
}

(new MapperBuilder)->mapper()->map(a::class, 'a a');
```

Yields: `PHP Fatal error:  Uncaught CuyZ\Valinor\Mapper\TypeTreeMapperError: Could not map type `a`. An error occurred at path *root*: Value 'a a' does not match string value 'aa'. in /home/daniil/repos/valinor/src/Mapper/TypeTreeMapper.php:29`

**Comment by romm** [comment]
Hi @danog thanks for the report and the examples.

I reworked the type parser, it is now more robust and fixes the issues described here.

Thanks for your patience!
