### ISSUE TITLE
Classes with arrays of classes dont work in PHP7.4

### ISSUE THREAD

**Issue by marioquartz** [CuyZ/Valinor#31]
I have a series of classes with multiples properties, when its a string or other class there are no problem.
But when a class have an array of other classes the mapper ignores that

Example:
Raw Json: '{"urls":[{"expanded_url":"https://example.com"}]}'
Class to be mapped:
```php
<?php

namespace App\Api\Twitter\Hint;

final class Entities
{
    /** @var Url[] $urls */
    public array $urls;

    public function __construct(
        /** @var Url[] $urls */
        array $urls
    )
    {
        /** @var Url[] $urls */
        $this->urls=$urls;
    }

    /**
     * @return Url[]
     */
    public function getUrls(): array
    {
        return $this->urls;
    }
}
```
And
```php
<?php

namespace App\Api\Twitter\Hint;

class Url
{
    public string $expanded_url;

    public function __construct(
        string $expanded_url
    )
    {
        $this->expanded_url=$expanded_url;
    }

    /**
     * @return string
     */
    public function getExpandedUrl(): string
    {
        return $this->expanded_url;
    }
}
```
property urls converts in a normal array with a normal array inside. I tested the class Url and work without problem. So, the problem appears when used with an array of classes.

**Comment by romm** [comment]
Hi @marioquartz, I believe the issue is that you use the annotation `@var` in your constructor's docblock. You should try this instead:

```php
<?php
final class Entities
{
    /** @var Url[] */
    public array $urls;

    /**
     * @param Url[] $urls
     */
    public function __construct(array $urls)
    {
        $this->urls = $urls;
    }
}
```

Or, if you're using PHP 8.0+ you might use [promoted properties](https://stitcher.io/blog/constructor-promotion-in-php-8):

```php
final class Entities
{
    /**
     * @param Url[] $urls
     */
    public function __construct(
        /** @var Url[] */
        public array $urls
    ) { }
}

```

**Comment by marioquartz** [comment]
First only use annotation in the first "public var $urls" But for desesperation i annotated every use of $urls i even duplicated with @psalm-var 

I tested your proposal and works. Thanks

**Comment by romm** [comment]
I'm glad it solved your issue. 😉
