### ISSUE TITLE
Must registered constructors be pure?

### ISSUE THREAD

**Issue by AndrolGenhald** [CuyZ/Valinor#311]
`MapperBuilder::registerConstructor` has the annotation `@psalm-param pure-callable|class-string ...$constructors`, which seems a bit odd to me. Is there a reason constructors must be pure? Most libraries don't mark their `__construct` functions as pure so it's often difficult to abide by that requirement, and when using `class-string` it's still going to be calling impure `__construct` functions without complaint anyway.

**Comment by romm** [comment]
Hi @AndrolGenhald sorry for the late answer; making the mapper pure was discussed in #192. I understand that there are limitations in static analysis concerning potential impure `__construct` constructors, but that's the best that can be done here, at least for now.

Closing for now, feel free to re-open if you think something could be done about this.
