### ISSUE TITLE
Union literal keys are not allowed for some reason

### ISSUE THREAD

**Issue by danog** [CuyZ/Valinor#312]
```
<?php

use CuyZ\Valinor\MapperBuilder;

require 'vendor/autoload.php';

(new MapperBuilder)->mapper()->map('array<"a"|"b", true>', ['a' => true]);

```

throws "Could not parse the type `array<"a"|"b", true>` that should be mapped: Invalid key type `"a"|"b"` for `array<"a"|"b", true>`. It must be one of `array-key`, `int` or `string`."

**Comment by romm** [comment]
Hi @danog thanks for the report! This should be fixed with #406 and will be part of the next release. 😉
