### ISSUE TITLE
unlink(valinor//mixed/.valinor.tmp/2fb94516664ef9d28156b38c079b4ae6) No such file or directory

### ISSUE THREAD

**Issue by eigan** [CuyZ/Valinor#328]
```
src/Cache/Compiled/CompiledPhpFileCache.php(99): unlink()
```

![image](https://user-images.githubusercontent.com/41789/213161127-e57e811c-593a-44c0-bf67-f6d0c2a9f979.png)

Laravel uses `set_error_handler` which receives the exception even though `@` is used. Which then logs and crashes the request.

https://www.php.net/manual/en/language.operators.errorcontrol.php
> If a custom error handler function is set with [set_error_handler()](https://www.php.net/manual/en/function.set-error-handler.php), it will still be called even though the diagnostic has been suppressed.

**Comment by romm** [comment]
Hi @eigan thanks for the report. This issue should be fixed with #346 and will be part of the next release. 😉
