### ISSUE TITLE
Accept ServerRequestInterface and InputInterface as source

### ISSUE THREAD

**Issue by delolmo** [CuyZ/Valinor#333]
I'd like to dicuss the possibility of creating additional sources for `Psr\Http\Message\ServerRequestInterface` and `Symfony\Console\Command\Command`.

Do you think this will give the library more value?

The specific use case I was thinking about is using the Mapper to create strongly-typed DTOs automatically inside the Command or at the Controller level.

For example, the following could be a rough draft for an InputSource:

```php
<?php

declare(strict_types=1);

namespace CuyZ\Valinor\Mapper\Source;

use ArrayObject;
use IteratorAggregate;
use Symfony\Component\Console\Input\InputInterface as Input;
use Traversable;

use function array_merge;

final class InputSource implements IteratorAggregate
{
    public function __construct(
        private Input $input,
    ) {
    }

    public function getInput(): Input
    {
        return $this->input;
    }

    public function getIterator(): Traversable
    {
        $input = $this->getInput();

        $array = array_merge($input->getOptions(), $input->getArguments());

        return new ArrayObject($array);
    }
}
```

And for a ServerRequestSource:

```php
<?php

declare(strict_types=1);

namespace CuyZ\Valinor\Mapper\Source;

use ArrayObject;
use IteratorAggregate;
use Psr\Http\Message\ServerRequestInterface as Request;
use Traversable;

use function array_merge;
use function is_array;

final class ServerRequestSource implements IteratorAggregate
{
    public function __construct(
        private Request $request,
    ) {
    }

    public function getIterator(): Traversable
    {
        $method = $request->getMethod();

        $queryParams = $this->getRequest()->getQueryParams();

        $parsedBody = $this->getRequest()->getParsedBody();

        if (! is_array($parsedBody)) {
            return $queryParams;
        }

        $array = array_merge($parsedBody, $queryParams);

        return new ArrayObject($array);
    }

    public function getRequest(): Request
    {
        return $this->request;
    }
}

```
Thoughts?

**Comment by romm** [comment]
Hi @delolmo, this is an excellent example of how iterators can be used with the library. 

For the future of the project I plan to create bundles/plugins for frameworks, so something similar to what you posted will probably land in these packages, but wont be imported in the core of the library.

Thank you for the suggestion, I close the issue but keep it in my mind for future reference. 😉

**Comment by delolmo** [comment]
I just published two packages, [delolmo/valinor-http-message](https://github.com/delolmo/valinor-http-message) and [delolmo/valinor-console](https://github.com/delolmo/valinor-consnole), in case anyone ones to use this implementation. Will be happy to transition to the bundles/plugins approach @romm when you are ready. Good job with the library!
