### ISSUE TITLE
Array key cannot contain class name

### ISSUE THREAD

**Issue by danog** [CuyZ/Valinor#337]
```
<?php

use CuyZ\Valinor\MapperBuilder;

require 'vendor/autoload.php';

class Test {
}

(new MapperBuilder)->mapper()->map('array{Test: string}', ['Test' => 'b']);
```

Fails with Uncaught CuyZ\Valinor\Mapper\Exception\InvalidMappingTypeSignature: Could not parse the type `array{Test: string}` that should be mapped: Missing second colon symbol for class constant `Test::string`.

Quoting the `Test` key fixes the issue temporarily.

**Comment by romm** [comment]
Hey there, thanks for the report! This issue should be fixed with #399 and will be part of the next release. 😉
