### ISSUE TITLE
Template parsing for constructors

### ISSUE THREAD

**Issue by boesing** [CuyZ/Valinor#340]
Hey there,

I am currently thinking about a generic way to pass constructors for specific interfaces in our project (as we try to keep our application kinda decoupled).

So what I was thinking about is something like this:

```php
/**
 * @template T of object
 */
interface InterfaceFactoryInterface
{
    /** @return T */
    public function __invoke(mixed $value): object;
}

/** @template-implements InterfaceFactoryInterface<stdClass> */
final class MySpecificClassFactory implements InterfaceFactoryInterface
{
    public function __invoke(mixed $value): object
    {
        // do assertions (which will be handled by valinor later on, right?)
        return new stdClass();
    } 
}


final class MappingSignature
{
     public function __construct(
         public readonly stdClass $objectToBeMapped,
     ) {}
}

$builder = new MapperBuilder();
$builder->registerConstructor(MySpecificClassFactory::class);

$source = Source::json('{"object": "whatever"}');
$mapper = $builder->mapper()->map(MappingSignature::class, $source);

assert($mapper->object instanceOf stdClass);
```

----

As of now, valinor is not able to read the `template` parameter from the `MySpecificClassFactory`. Is this something which I could contribute to this project or was that an explicit decision?

The main reason I'd love to do that is that I do want our developers to properly type their factories for specific interfaces.

Let me know what you think, happy to get any feedback here.

Thanks in advance.

**Comment by romm** [comment]
Hi @boesing, from what I understand the example you gave could be achieved with something similar to:

```php
final class MySpecificClassFactory
{
    public function __invoke(string $value): stdClass
    {
        if ($value === 'foo') {
            throw MessageBuilder::newError('nope')->build();
        }

        $object = new stdClass();
        $object->value = $value;

        return $object;
    }
}

final class MappingSignature
{
    public function __construct(
        public readonly stdClass $objectToBeMapped,
    ) {}
}

$source = Source::json('{"objectToBeMapped": "bar"}');
$result = (new MapperBuilder())
    ->registerConstructor(new MySpecificClassFactory())
    ->mapper()
    ->map(MappingSignature::class, $source);

assert($result->objectToBeMapped instanceof stdClass);
assert($result->objectToBeMapped->value === 'bar');
```

Registering constructors for interfaces is currently not supported (as stated in https://github.com/CuyZ/Valinor/issues/217#issuecomment-1257002038). This is on my todo list, if this is what you need I'll probably give this topic a higher priority.

**Comment by boesing** [comment]
Yeah, I understand that the return value could be added. But I'd prefer an Interface (from application perspective) so that devs can already run psalm to verify if their return value matches the expectation. 

Basically the feature described in your linked issue would be what I need - besides the fact that I'd love to have that templated Interface in our upstream project for re-usages. 
we will have plenty of factories and having a generic interface would be awesome. 

Was also thinking about adding the value type more specific - such as `non-empty-string` or `positive-int` and such.

**Comment by boesing** [comment]
Pretty sure I did not properly handle every edge-case. Thats just a quick scribble on how I think it could work. esp. when it comes to more complex Interfaces to be instantiated by a json object with multiple properties, this example above wont fit anymore (unless some1 requires an array shape for example). 

Thats why I'd love to gather ideas and stuff. 👌🏻

**Comment by romm** [comment]
Hi @boesing, after reading https://github.com/CuyZ/Valinor/issues/340#issuecomment-1419032948 I came to the conclusion that what is asked here is not possible.

Valinor acts as a simple static analyzer to narrow down every type information it needs to use. The `->registerConstructor(...array_values($configuration->interfaceFactories))` line is way too complex for Valinor's engine, as the lib should be able to potentially analyze the whole application's codebase to understand what is going on (which is obviously not possible).

Maybe #514 could help achieve what you need?

I'm closing, feel free to reopen if you think this topic still makes sense. 😉
