### ISSUE TITLE
Interfaces should support type aliases

### ISSUE THREAD

**Issue by danog** [CuyZ/Valinor#353]
This code:
```php
<?php

use CuyZ\Valinor\MapperBuilder;

require 'vendor/autoload.php';
/** @psalm-type TT=int */
interface a {}
/** @psalm-import-type TT from a */
class Test {
    /** @param TT $a */
    public function __construct($a)
    {

    }
}

(new MapperBuilder)->mapper()->map('Test', 123);
```

Throws the following exception: Importing a type alias can only be done with classes, `a` was given in class `Test`. in /home/daniil/repos/valinor/src/Definition/Repository/Reflection/ReflectionClassDefinitionRepository.php:198

**Comment by romm** [comment]
That was not such a big change, should be fixed by #507. Enjoy!
