### ISSUE TITLE
Top-level union with allowSuperfluousKeys and overlapping types behaves unpredictably

### ISSUE THREAD

**Issue by TimWolla** [CuyZ/Valinor#358]
Consider the following example:

```php
<?php

use CuyZ\Valinor\MapperBuilder;

require('vendor/autoload.php');

class Foo
{
    public function __construct(
        private readonly string $foo,
        private readonly string $baz,
    ) {
    }
}

class Bar
{
    public function __construct(
        private readonly string $bar,
        private readonly string $baz,
    ) {
    }
}

class Any
{
    public function __construct()
    {
    }
}

try {
    $payload = (new MapperBuilder())
        ->allowSuperfluousKeys()
        ->mapper()
        ->map(
            "Bar | Foo | Any",
            [
                "foo" => "foo",
                "baz" => "baz",
                "bar" => "bar",
            ]
        );

    var_dump($payload);
} catch (\CuyZ\Valinor\Mapper\MappingError $error) {
    $messages = \CuyZ\Valinor\Mapper\Tree\Message\Messages::flattenFromNode(
        $error->node()
    );

    foreach ($messages as $message) {
        echo $message;
    }
}
```

The input is valid for each of the three types in the union, due to allowing superfluous keys. It currently emits the fairly non-descript error:

> Invalid value array{foo: 'foo', baz: 'baz', bar: 'bar'}.

When I remove any of the two property in `Bar` it consistently maps into `Foo`. If I add a `$foo` property to `Bar`, it consistently maps into `Bar`. If I remove both `foo` and `bar` from the input it consistently maps into `Any`.

I would expect Valinor to behave consistently with overlapping types in an union. Either the input should always be rejected if multiple union cases match, or (any this would be my preference) the first matching case should be used.

My real-world use case is mapping OAuth 1 response query strings. The same route should both handle the two possible response cases („Success“ and „Error“) and a fallback that accepts anything and starts the OAuth flow (the „Any“ type in the example above). This would allow me to match each of the three cases by checking `$payload instanceof Success` etc, effectively acting as a tagged union.

Because I cannot guarantee that the query string is completely clean (e.g. due to google analytics tracking parameters), I am allowing superfluous keys. During testing to make sure that the `Any` type only matches if no other type matches, I stumbled across this issue.

**Comment by romm** [comment]
Hi @TimWolla, sorry for the late answer.

I tried to understand your usecase but I think the "Foo"/"Bar" naming doesn't help. From the example you posted, it seems to me that the results are correct:

```php
[
    "foo" => "foo",
    "baz" => "baz",
    "bar" => "bar",
] // Collision because matches both `Foo` and `Bar`

[
    "foo" => "foo",
    "baz" => "baz",
    "superfluous_key" => "anything",
] // Maps to `Foo`

[
    "bar" => "bar",
    "baz" => "baz",
    "superfluous_key" => "anything",
] // Maps to `Bar`

[
    "something" => "some value",
    "another" => "other value",
] // Maps to `Any`
```

This looks consistent and predictable to me, what am I missing here?

**Comment by TimWolla** [comment]
@romm It's been a while, so it's not really fresh in my mind, but based on what I wrote in the issue, my main problem here is:

> It currently emits the fairly non-descript error:

The error message is already greatly improved with your branch, thanks!

> When I remove any of the two property in `Bar` it consistently maps into `Foo`.

1. Given the example code: An error message is emitted.
2. Removing the `private readonly string $bar,` from `Bar` makes the error message go away, but the input is still valid for each of Foo, Bar, and Any.

The description in your PR says that “the one with the most children node will be prioritized, as it is considered the most specific type”, which probably is a reasonable decision to take. Taking the leftmost match would possibly allow for greater developer control, though.

> During testing to make sure that the `Any` type only matches if no other type matches, I stumbled across this issue.

Based on my understanding of that sentence, the test case described in the initial issue is not a real-world test case. I just wanted to test various edge cases to see what Valinor does there.

--------------

I guess this issue is solved, unless you have follow-up questions?

**Comment by TimWolla** [comment]
For reference my mentioned real-world test case (“OAuth 1 response”) would probably look something like this:

```
<?php

use CuyZ\Valinor\MapperBuilder;

require('vendor/autoload.php');

class Oauth1Success
{
    public function __construct(
        private readonly string $oauth_token,
        private readonly string $oauth_verifier,
    ) {
    }
}

class Oauth1Failure
{
    public function __construct(
        private readonly string $denied,
    ) {
    }
}

class Any
{
    public function __construct()
    {
    }
}

foreach ([
    [
        "oauth_token" => "foo",
        "oauth_verifier" => "foo",
        "utm_source" => "foo",
    ],
    [
        "denied" => "foo",
        "utm_source" => "foo",
    ],
    [
        "utm_source" => "foo",
    ],
    [
    ]
] as $input) {
    try {
        $mapper = (new MapperBuilder())
            ->allowSuperfluousKeys()
            ->mapper();


        $payload = $mapper->map(
            "Oauth1Success | Oauth1Failure | Any",
            $input
        );

        var_dump($payload);
    } catch (\CuyZ\Valinor\Mapper\MappingError $error) {
        $messages = \CuyZ\Valinor\Mapper\Tree\Message\Messages::flattenFromNode(
            $error->node()
        );

        foreach ($messages as $message) {
            echo $message;
        }
    }
}
```

**Comment by romm** [comment]
> The error message is already greatly improved with your branch, thanks!

Note that as stated in https://github.com/CuyZ/Valinor/pull/493#discussion_r1526065994 the error message still lacks some information when mapping to an object. There's room for improvement and I plan to take care of it when I have time. 😊

> Taking the leftmost match would possibly allow for greater developer control, though.

Right, we could change this behavior in the future, if that is really needed. But I guess these are rare use-cases.

Thanks for the detailed answer!

**Comment by TimWolla** [comment]
> Note […] the error message still lacks some information when mapping to an object.

At least the important bit “matches two or more types from union” is clearly stated now, whereas previously it just said “invalid value”.
