### ISSUE TITLE
Issue with `float` and `int` values when using `json_encode` and `json_decode`

### ISSUE THREAD

**Issue by boesing** [CuyZ/Valinor#360]
Hey there,

I realized some issues when using `cuyz/valinor` in combination with some API responses.
For `float`, both `int` and `float` values are acceptable values in PHP:

https://3v4l.org/YmsMI#v8.1.16

Using `json_encode` properly creates a response with float `0.0` in both cases (I guess due to the fact that the default `float_precision` is 1, but I have no clue:

```json
{"floatProperty":0.0}
```

So having this response, creating an instance of the object works without issues.
In case, the property is not strictly typed, `json_encode` will convert the value to integer even tho it was a `float` beforehand:

https://3v4l.org/3Hmh8#v8.1.16

This leads to type-issues in valinor even tho, passing integer to float properties should be absolutely fine (from a type-perspective - at least in PHP, no clue if thats also the case in other languages tho).

I have a use-case, where I can't modify the API and thus, have to somewhat handle the type on my own.

I now have a workaround by allowing `int` to the `__construct` and then casting it to float:

```php
final class ObjectWithFloatProperty
{
    public readonly float $floatProperty;

    public function __construct(float|int $floatProperty)
    {
         $this->floatProperty = (float) $floatProperty;
    }
}
```

Do you have any problems with allowing `int` for `float` values or should we stick with the workaround here?
Feedback is very welcome.

**Comment by romm** [comment]
Hi @boesing sorry for the late answer.

If I understand correctly, the issue is something similar to:

```php
(new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map('float', 0);

// Could not map type `float`. An error occurred at path *root*: Value 0 is not a valid float.
```

> Do you have any problems with allowing int for float values

I think Valinor has the correct behavior here; I may be wrong but the `json_encode` behavior seems incorrect.

---

Unfortunately unless we find a better solution, you'll have to maintain a workaround for this. 🫤

There is something I'm not sure I understand though, why do you have to use `json_encode`? I know that in some cases you get `stdClass` with some PHP libraries/functions, could you rather cast the object to `array` and give it to the mapper?

https://3v4l.org/LgJGn

```php
$objectWithFloatProperty = json_decode('{"floatProperty":0.0}');

var_dump(
    $objectWithFloatProperty,
    (array)$objectWithFloatProperty,
    json_encode($objectWithFloatProperty)
);

/*
object(stdClass)#1 (1) {
  ["floatProperty"]=>
  float(0)
}
array(1) {
  ["floatProperty"]=>
  float(0)
}
string(19) "{"floatProperty":0}"
*/
```

Thanks for the report!

**Comment by boesing** [comment]
> I may be wrong but the json_encode behavior seems incorrect.

I can only assume that the API which we are calling is just using `json_encode` with flag(s) `JSON_THROW_ON_ERROR`. If `JSON_PRESERVE_ZERO_FRACTION ` would be used, it keeps the `0.0` as expected tho. There was an RFC for PHP 7.0 https://wiki.php.net/rfc/json_preserve_fractional_part which actually provided that flag. Since we do not have a real way to tell the API we are consuming to add this flag (maybe they can't due to whatever reason), that probably won't change.

What I actually do not understand is, why PHP allows `int` to be passed to float (even in `strict_mode`). The only reason I can think of is, that if there is no fraction available, it is automatically assumed as `*.0` and thus, some casting happens within PHP internals and that is, why I was thinking that Valinor could support this behavior as it is also allowed in PHP from a type-perspective. Even [psalm](https://psalm.dev/r/51c4446eb9) actually allows int to be passed to `float`.

----

> There is something I'm not sure I understand though, why do you have to use json_encode? 

I do not have to use `json_encode`, that was just to provide an example. The API we are calling returns a JSON payload which we are simply passing to valinor using `(string) $stream`. It works most of the time but sometimes, there might be an integer without the `ZERO_FRACTION` and that is why I can only assume that the API internally uses `json_encode` without `JSON_PRESERVE_ZERO_FRACTION` flag - but not sure if its even PHP, maybe there are even other JSON encoder out there which convert float without fraction to int.

**Comment by romm** [comment]
After giving it some thoughts I think you're right, with #370 float types will now accept integer values. Thanks for all the explanations!

**Comment by boesing** [comment]
Thank you for considering this! ❤️
