### ISSUE TITLE
InvalidJson and SourceException are flagged as internal without a valid alternative

### ISSUE THREAD

**Issue by BGehrels** [CuyZ/Valinor#361]
Hey everyone.

it would be great to have some non-internal Exception Interface that we can use to explicitly catch source syntax exceptions.

Why? 
- We want syntax errors (invalid json) to be reported back to the client with a 400 status code and a proper error message
- We do not want other, arbitrary RuntimeExceptions to have their error message leaked to our clients.
- Exceptions, that are not related to the input syntax should be returned as HTTP status 500.

At the moment, we solve this as follows:

        try {
            return (new MapperBuilder())
                ->mapper()
                ->map(DtoClass::class, new JsonSource($requestBody);
        } catch (MappingError $e) {
            throw new BadRequestException(transformToMeaningfulMessage($e));
        } catch (InvalidJson $e) {
            throw new BadRequestException($e->getMessage());
        } catch (RuntimeException) {
            throw new InternalErrorException();
        }

While this works fine, the IDE reports that we are not supposed to use `InvalidJson` because it is flagged as `@internal`. The only other options in the inheritance tree are `RuntimeException` (which is to broad) and `SourceException` (which is flagged as `@internal`) as well.

Proposals:

- SourceException could be made non-internal or
- InvalidJson could be made non-internal or
- Another non-internal marker interface could be introduced - and InvaldJson would implement it

**Comment by BGehrels** [comment]
Great, thank you, that helps a lot! 

It would now be great if `TreeMapper.map(...)` would also declare it in the `throws` annotation as the lack of it triggers yet another warning:

> Exception 'InvalidSource' is never thrown in the corresponding 'try' block

**Comment by romm** [comment]
Hi @BGehrels sorry for the late answer.

The method `TreeMapper::map()` actually has nothing to do with the `InvalidSource` interface, as the given input can be anything. In fact, the library gives you access to the `Source` class for convenience, and the provided constructor methods actually throw the `InvalidSource`. So I don't really get your issue there, if you don't use `Source` in your `try` block, then there should not be a `catch(InvalidSource) { … }` at all. 🤔
