### ISSUE TITLE
Issue with array-key & mixed

### ISSUE THREAD

**Issue by jenky** [CuyZ/Valinor#363]
I got this error while using [ramsey/collection](https://github.com/ramsey/collection). 

```
Types for parameter `Ramsey\\Collection\\AbstractArray::offsetExists($offset)` do not match: `array-key` (docblock) does not accept `mixed` (native).
```

Perhaps the opposite should be added?

https://github.com/CuyZ/Valinor/blob/eebd3141d89b1a5a7b6bd5388159bf736c89c8c6/src/Definition/Repository/Reflection/ReflectionTypeResolver.php#L47

```php
&& ! $typeFromDocBlock->matches($nativeType)
&& ! $nativeType->matches($nativeType)
```

**Comment by romm** [comment]
Thanks for the report! Should be fixed by #368. 😉
