### ISSUE TITLE
Allow multiple object builders with same argument names but different types

### ISSUE THREAD

**Issue by AndrolGenhald** [CuyZ/Valinor#377]
The following code currently fails for both list items with a `SeveralObjectBuildersFound` exception from `FilteredObjectBuilder`. Since the types don't overlap there shouldn't be any ambiguity, so I expected this to work. I suppose this might actually be a bit difficult since if `FilteredObjectBuilder` filters based on argument types it would no longer show the same error for an incorrect type, it would instead throw a `CannotFindObjectBuilder` exception.

```php
<?php

include "vendor/autoload.php";

class Foo
{
    public function __construct(public int $value) {}
}

class Bar
{
    public function __construct(public string $value) {}
}

var_dump(
    (new CuyZ\Valinor\MapperBuilder())
        ->mapper()
        ->map("list<Foo|Bar>", ["foobar", 123])
);
```

**Comment by romm** [comment]
Hi @AndrolGenhald, you'll be pleased to know that this has been fixed by #552!
