### ISSUE TITLE
Enum cases and union type

### ISSUE THREAD

**Issue by szado** [CuyZ/Valinor#385]
It's not possible to define a type as union of several enum cases:

```
enum Color {
   case Red;
   case Green;
   case Blue;
}

class Dto {
   public function __construct(
      /** @var Color::Red | Color::Green */
      public Color $color;
   ) {}
}
```

Attempting to parse it results in an error: `Could not map type `Dto`. An error occurred at path color: Invalid value 'Green'`. I'm sure it used to work.

**Comment by romm** [comment]
Hey there, this issue should be fixed with #385 (which was released with [1.11.0](https://github.com/CuyZ/Valinor/releases/tag/1.11.0).

Sorry it took that long, enjoy!
