### ISSUE TITLE
Attributes in cache files?

### ISSUE THREAD

**Issue by boesing** [CuyZ/Valinor#393]
Hey there,

maybe I am missing something, but the cache files do also contain informations for attributes. 
I am not 100% sure why valinor needs attributes as there is no attribute support regarding type addition from what I can see?

We recently ran into an issue where our OpenAPI Attributes of a request object were persisted in the cache since we do generate the cache at build time while dev dependencies are still available. We changed this to non-dev composer dependencies now but I still wonder why attributes are even parsed at all.

**Comment by romm** [comment]
Hi @boesing, thanks for the report.

Attributes support comes from a long time ago, when I was not sure whether mapping behaviors could be controlled by attributes (which is the case in some other PHP mapping libraries). Currently, attributes are only used for the [dynamic constructor feature](https://valinor.cuyz.io/latest/how-to/use-custom-object-constructors/#dynamic-constructors), but I plan to add support for a `Constructor` attribute which could be used to ease constructor registration, among maybe other features, so removing it is not possible.

I'd better like to know what was the issue you ran into?

**Comment by romm** [comment]
Hi @boesing after reading again this issue I understood what was going on.

I opened #408, which should fix it. Any chance you review it and/or test it on your app to see if it fixes the problem?

Thanks!

**Comment by boesing** [comment]
Hey @romm ,

sorry for not responding. 
I'll have a look once I find some time. One thing what for example jms/serializer does, it checks for the attributes namespace so it only caches its own attributes instead of any attribute. That is what I would expect here as well, since you do only care for valinor specific attributes from what I understand, right?
Maybe that could be a thing as well, so you dont have to care about unavailable attributes at runtime? Just dropping my 2 cents here but I will have a look on the Patch as well. 
Thanks for considering this.

Regards!

**Comment by romm** [comment]
Hi @boesing, thanks for your valuable input.

You're right, for now the library only uses one internal attribute, your suggestion to only accept internally namespaced attributes makes total sense.

However, custom attributes could be used in the future; although it is often advised not to over-engineer things in advance, this feature was coded at a time (before the first public beta release) where I had plan for third party attributes that implemented Valinor-namespaced interfaces.

For this reason, I prefer to keep the feature in place — at least for now — and fix small bugs like the one you just submitted, in case we need it for future attribute features. 😉
