### ISSUE TITLE
Ensure cache dirs are always present

### ISSUE THREAD

**Issue by simPod** [CuyZ/Valinor#401]
From time to time after a fresh app deploy I encountered

> CuyZ\Valinor\Cache\Exception\CacheDirectoryNotWritable
> Provided directory `/home/www/app/13925/var/cache/prod/Valinor/classes` is not writable.

We should ensure those directories are always present on app cache warmup.

They are ultimately created but when there's higher app load, I presume some race condition occurs and this errors pops up before the dir is created.

**Comment by romm** [comment]
Thanks for the report! Should be fixed by #407 which will be part of the next release. 😉
