### ISSUE TITLE
Roll a 0.2.1 release containing date format fixes

### ISSUE THREAD

**Issue by brandonsavage** [CuyZ/Valinor#42]
As presently designed, the example code in the README file *does not work* as written without the patch introduced in 179ba3df299be62b0eac24a80e9d4d56d0bb5074. Its my suggestion that we roll a 0.2.1 release to incorporate that change (you can cherry-pick if you have not-ready features waiting in `master`). I want to avoid folks coming and trying the library only to discover that the example code doesn't work quite right, and walking away from a beautiful library with a ton of possibility. What do you think?

**Comment by romm** [comment]
I think you're absolutely right, just released new minor version. 🙂
