### ISSUE TITLE
Registering ramseys `UuidInterface` seems complex

### ISSUE THREAD

**Issue by boesing** [CuyZ/Valinor#426]
Hey there,

one thing I am still missing and unable to understand why it seems to be that complex:
Creating interface instances based on factory methods.

I do have objects implementing `UuidInterface` (from `ramsey/uuid`).
The base implementation for `Uuid` or for concrete versions do have a `__construct` not consuming `string`.

So lets say I do have:

```php
final class Foo
{
     public UuidInterface $uuid;
}
```

and a JSON source like: `{"uuid":"be3e4a03-1668-43c1-806a-f2903b54c9e0"}`

To have this working as expected, I do have to register a constructor **and** have to `infer` the interface like this:

```php
use Ramsey\Uuid\UuidInterface;
use Ramsey\Uuid\Uuid;

$this->mapperBuilder
    ->infer(UuidInterface::class, fn (string $value): string => Uuid::class)
    ->registerConstructor(fn (string $value): UuidInterface => Uuid::fromString($value));
```

---

Why is the `infer` part necessary? Is that, because `UuidInterface` returned from the callable is not a concrete class? Why would that be necessary? I'd expect that the constructor takes over and therefore I would not expect valinor to really care about the implementation.

Can you probably elaborate or do I just use this whole stuff wrong?
Thanks

**Comment by romm** [comment]
Hi @boesing, you're using the library correctly. It seems complex because this is a current limitation of the library: constructors are not analyzed during interface inferring. As I said in https://github.com/CuyZ/Valinor/issues/217#issuecomment-1257002038 I plan to support it, so I'll leave this issue open. 🙂 

Thanks for the report!
