### ISSUE TITLE
Cannot import a type alias from unknown class

### ISSUE THREAD

**Issue by loevgaard** [CuyZ/Valinor#439]
I am getting this exception:

```
Cannot import a type alias from unknown class `this` in class `Setono\EditorJS\Block\Block`. 
```

When I call this method: https://github.com/Setono/editorjs-php/blob/1.x/src/Parser/Parser.php#L41 with the following content:

```json
{"time":1697525752042,"blocks":[{"id":"M97WRR3EL6","type":"paragraph","data":{"text":"sadfasdf"}}],"version":"2.26.5"}
```

I can confirm that I don't get this exception in `1.6.0`, but I get it in `1.6.1`, so I my guess is it's related to this https://github.com/CuyZ/Valinor/commit/c231020d6e393f6b1ea5758cb9fbeee469ac3d5b

**Comment by loevgaard** [comment]
Thank you very much! Will try it out :)

**Comment by romm** [comment]
Version `1.7.0` [has just been released](https://github.com/CuyZ/Valinor/releases/tag/1.7.0)! Enjoy. 😎
