### ISSUE TITLE
DocParser::importedTypeAliases leads to Cannot import a type alias from unknown class `either`

### ISSUE THREAD

**Issue by garbast** [CuyZ/Valinor#443]
DocParser::importedTypeAliases uses in a preg_match

`if (! preg_match('/\s*(?<name>[a-zA-Z]\w*)\s*from\s*(?<class>\w+)/', $case, $matches)) {`

This results in the error "Cannot import a type alias from unknown class `either`" with the following doc comment

```
/**
 * A generic Domain Object.
 *
 * All Model domain objects need to inherit from either AbstractEntity or AbstractValueObject, as this provides important framework information.
 * @internal only to be used within Extbase, not part of TYPO3 Core API.
 */
 ```

The preg match needs to be enhanced to not only search for from in an comment, to prevent such an error.

The comment was taken from `TYPO3\CMS\Extbase\DomainObject\AbstractDomainObject` from the package typo3/cms-extbase.

**Comment by romm** [comment]
Hi @garbast, thanks for the report.

The issue was fixed with #437, I'm doing a release that should be live within the hour, you can then update and the problem should be gone.

**Comment by romm** [comment]
Version `1.7.0` [has just been released](https://github.com/CuyZ/Valinor/releases/tag/1.7.0)! Enjoy. 😎

**Comment by garbast** [comment]
Thanks for the quick reaction. Have a good one.
