### ISSUE TITLE
Leading zeros in numeric string leading to invalid integer

### ISSUE THREAD

**Issue by delolmo** [CuyZ/Valinor#454]
When trying to map a class such as:
```php

class DayOfMonth
{
    /** @param <1, 31> $day */
    public function __construct(private int $day) {}
}
```
with value "05" and flexible casting enabled, the following error message is returned:
```text
Could not map type `DayOfMonth`. An error occurred at path day: Value '05' is not a valid integer between 1 and 31.
```
Ideally, `string("05")` should be cast to `integer(5)` without problems.

**Comment by romm** [comment]
Hi @delolmo thanks for the report. This should be fixed with #458. 🙂
