### ISSUE TITLE
Feat: Allow providing own PSR-16 cache service

### ISSUE THREAD

**Issue by aurimasniekis** [CuyZ/Valinor#48]
I have been working on making a Symfony bundle for this library and thought it would be great if it was possible to inject my own PSR-16 cache service instead of using a file cache provided from Library.

With the current setup, I think it would be impossible without replicating a whole Container functionality.

Maybe it's better to replicate Container for situations where integrating with framework for e.g. Symfony.

**Comment by romm** [comment]
Hi @aurimasniekis, thanks for the suggestion. Before going any further, could you explain what would be the reasons to provide another PSR-16 implementation? For now, the cache is used only for compiled class definitions:

https://github.com/CuyZ/Valinor/blob/d2795bc6b9ee53f9896889cabc1006be2586b008/src/Library/Container.php#L144-L145

The generated PHP code seems to be the best performance-wise alternative. Maybe the way the PHP files are read/written could be problematic though, is that the reason why you raised this issue?

**Comment by aurimasniekis** [comment]
This is probably more practicality than a performance-wise alternative, the idea is to let the app/framework manage the caching of those classes instead of the library, this would allow different types of configurations when using a library with frameworks that have really extensive caching options. 

At the moment I am working on the bundle to integrate this library with Symfony with all its magic things, the code is still a work in progress https://github.com/framjet/php-valinor-bundle but I managed to make it run with cache warms up and similar goodies.

**Comment by romm** [comment]
Hi @aurimasniekis, this looks very nice! Could you add some lines in the README explaining how to use it in a Symfony environment?

From what I saw, you would need to inject your own cache implementation mainly for cache-warmup, am I right? I'm still struggling to see how useful this would be without having access to `\CuyZ\Valinor\Definition\Repository\ClassDefinitionRepository` as well. Could you give an example of how you would imagine it?

**Comment by romm** [comment]
Hi @aurimasniekis, I just submitted #132 which should meet your needs. If you're up to, I'd love to get some feedback on it. 🙂

**Comment by romm** [comment]
Closed with #132.
