### ISSUE TITLE
Use valinor for a assert() function use case

### ISSUE THREAD

**Issue by staabm** [CuyZ/Valinor#522]
to encapsulate valinor I want to create a few static methods, which make use of valinors super power but hides the library for the caller.

something like

```php
// utility
final class Typer {
    /**
     * @param mixed $var
     * @param literal-string $type
     *
     * @throws RuntimeException
     */
    static public function assert(string $type, $var): void {
        try {
            (new MapperBuilder())
                ->mapper()
                ->map($type, $var);
        } catch (\CuyZ\Valinor\Mapper\MappingError $e) {
            throw new RuntimeException($e->getMessage());
        }
    }
}

// caller
Typer::assert('non-empty-string', $email);
Typer::assert('array<int, string>', $addresses);
```

as you can see the idea is to narrow the type of `$var`, like other assertion libraries do.

it would be great if the PHPStan typing logic in [TreeMapperPHPStanExtension](https://github.com/CuyZ/Valinor/blob/master/qa/PHPStan/Extension/TreeMapperPHPStanExtension.php) could be extracted so I can re-use it for a TypeSpecifyingExtension, without the need of duplicating valinors internal PHPStan typing logic.

**Comment by staabm** [comment]
I think my request does not fit valinor. I will create a separate lib to implement my idea.

**Comment by romm** [comment]
Hi @staabm, I agree that your request goes beyond Valinor's scope. I'm interested in the solution you will provide, would you mind sharing it here when it's done? Do you think this kind of logic (inferring type directly from a variable/parameter content) could fit in PHPStan's core, somehow?

I also want to express my gratitude towards your work on OSS projects in general, I feel honored that you give Valinor a try. 🙂
