### ISSUE TITLE
Is it possible to infer class union (without interface)

### ISSUE THREAD

**Issue by simPod** [CuyZ/Valinor#528]
```php
final class Foo
{
    public function __construct(
        public Bar|Baz $a,
    ) {
    }
}
```

is it possible to somehow map value to `Bar|Baz`? I've found it's possible with [interfaces](https://valinor.cuyz.io/latest/how-to/infer-interfaces/) but did not find anything about class unions

**Comment by romm** [comment]
Hi @simPod, the documentation is (unfortunately) not very precise about this, but you can use objects in union types, as long as these objects do not have colliding constructors (=constructors with the same arguments names).

I'll definitely consider rewriting the whole chapter about types reference in the documentation. 🙂
