### ISSUE TITLE
Fix phpstan error with Symfony Uuid in MapperBuilder class and registerConstructor method

### ISSUE THREAD

**Issue by pchelk1n** [CuyZ/Valinor#540]
> Parameter 1 ...$constructors of method CuyZ\Valinor\MapperBuilder::registerConstructor() expects (pure-callable(): mixed)|class-string, Closure(string): Symfony\Component\Uid\Uuid given

```
use Symfony\Component\Uid\Uuid;
//....
$builder->registerConstructor(Uuid::fromString(...))
```

**Comment by psprokofiev** [comment]
phpstan still throws  

> Parameter #1 ...$constructors of method CuyZ\Valinor\MapperBuilder::registerConstructor() expects (pure-callable(): mixed)|class-string, Closure(string): Symfony\Component\Uid\Uuid given.

**Comment by romm** [comment]
@psprokofiev looks like a cache issue, as we can clearly see that [CuyZ\Valinor\MapperBuilder::registerConstructor()](https://github.com/CuyZ/Valinor/blob/b15d1a50c3783b47b743385431899f2696ffebd6/src/MapperBuilder.php#L198) does not require a `pure-callable` anymore.

**Comment by psprokofiev** [comment]
yeap, my bad, I've installed dev-master of the bundle  
so extremely looking for released of the valinor and it's bundle )
