### ISSUE TITLE
Class "Money\Money\Currency" does not exist

### ISSUE THREAD

**Issue by dejagersh** [CuyZ/Valinor#554]
Hi, maybe I am doing something wrong but I get the following error:

```
Class "Money\Money\Currency" does not exist
```

reproducible example:

```php
<?php

declare(strict_types=1);

use CuyZ\Valinor\Mapper\Source\Source;
use CuyZ\Valinor\MapperBuilder;
use Money\Currency;
use Money\Money;

require_once __DIR__ . '/vendor/autoload.php';

readonly class Transaction
{
    public Currency $currency;

    public string $amount;

    public function foobar(): Money
    {
        return new Money($this->amount, $this->currency);
    }
}

$mapper = (new MapperBuilder())
    ->allowSuperfluousKeys()
    ->mapper();

$mapper->map(
    Transaction::class,
    Source::array([
        'currency' => 'USD',
        'amount' => '100',
    ])
);
```

Any ideas on what I am doing wrong?

**Comment by romm** [comment]
Hi @dejagersh, looks like a bug related to the `Money\Money` class. I'll have a look ASAP to fix this, and keep you updated here. 😊

**Comment by dejagersh** [comment]
> Hi @dejagersh, looks like a bug related to the `Money\Money` class. I'll have a look ASAP to fix this, and keep you updated here. 😊

Thank you! Some extra context that might be useful: when I remove the `foobar()` method (and the `Money` import), it works.

**Comment by stof** [comment]
This looks like Valinor tries to use the `use Money\Money` use statement to resolve the class name of the `use Money\Currency`, as if `Money\Currency` was used as an unqualified name in the file. But use statements are always fully qualified.

**Comment by romm** [comment]
@dejagersh could you checkout #555 and see if it solves your issue?

**Comment by dejagersh** [comment]
> @dejagersh could you checkout #555 and see if it solves your issue?

Works like a charm!

<img width="728" alt="image" src="https://github.com/user-attachments/assets/1b82f559-2af0-4bdd-bd37-9d66222dab30">

Tested it both in the empty project to make a reproducible example and in my prod project and looks good ✅

**Comment by romm** [comment]
Hi @dejagersh after [@stof's comment](https://github.com/CuyZ/Valinor/pull/555#issuecomment-2326158392) I changed the code. As it is a major change compared to what you tested, would you mind doing it again to check everything is alright?

**Comment by dejagersh** [comment]
> Hi @dejagersh after [@stof's comment](https://github.com/CuyZ/Valinor/pull/555#issuecomment-2326158392) I changed the code. As it is a major change compared to what you tested, would you mind doing it again to check everything is alright?

Sorry just now saw your comment. Just tested it, works fine!

**Comment by romm** [comment]
Great, thank you!
