### ISSUE TITLE
How to apply custom transformations?

### ISSUE THREAD

**Issue by danydev** [CuyZ/Valinor#64]
Context: as of today, I map my API REST request bodies from json to DTO by using Symfony's Forms. While it works fairly well, Symfony's Form are meant to handle forms. I would like to avoid their inherited complexity and limitations since are not the best fit for my use case, so I'm looking for an alternative and I want to try out Valinor.

Problem: I have cases where in the request I receive things like "productId" and I want my DTO to contain an object of class `Product` that should be retrieved by doing a query by id using the ORM. Is there an hook/way that I can build upon to fulfil this use case? I was looking for some sort of way to define the transformation/mapping for those custom cases, but I didn't find anything about it in the documentation.
Similarly I have cases where I receive monetary amounts as a string like "12.03" but in my DTO I want a `Money` object constructed with something like `new Money((float) $value)`, so I would need some sort of custom "type"/"mapping" for this as well.

What are Valinor recommendations in those cases?

**Comment by romm** [comment]
Hi @danydev!

>  I have cases where in the request I receive things like "productId" and I want my DTO to contain an object of class Product that should be retrieved by doing a query by id using the ORM. Is there an hook/way that I can build upon to fulfil this use case? I was looking for some sort of way to define the transformation/mapping for those custom cases, but I didn't find anything about it in the documentation.

I'm glad you asked this question actually. This is a "hidden" feature; it is not documented yet because I'm still not sure if I want it to stay in the library (at least as it is), so please be aware that the behavior I'll explain below could change in the future.

There is a `bind()` method that can be used with the mapper builder, that can explain the mapper how to create a certain type of object.

```php
return (new \CuyZ\Valinor\MapperBuilder())
    ->bind(function ($source): Product {
        if (! is_int($source)) {
            throw new \DomainException('Should be an int');
        }

        try {
            return $this->productRepository->find($source);
        } catch (SomeRepositoryException) {
            throw new \DomainException("Could not find product with id `$source`")
        }
    })
    ->mapper()
    ->map(SomeClass::class, [/* … */]);
```

Tell me if you can make it work, otherwise I'll try to help. 🙂 

> Similarly I have cases where I receive monetary amounts as a string like "12.03" but in my DTO I want a Money object constructed with something like new Money((float) $value), so I would need some sort of custom "type"/"mapping" for this as well.

This is a very basic usecase where this library will help: just type the property you want an instance of `Money` to be mapped to, and the mapper will do the job for you. If you need some assistance setting it up, don't hesitate.

**Comment by danydev** [comment]
Thanks for your response, the `bind` sounds promising. Also I assumed that the library couldn't create a Money because the sent type is a string, while the constructor has float (and I don't want to create a static method `fromString` in Money, just because a mapper needs it).

I do have another use case: sometime I create my DTO before allowing Symfony Form to do its magic, because I create it with some input contained in the url path, but then I would like to map other properties with the mapping from the json body. 
Example: let's say we have `POST /product/{productId}/line-items` and then the DTO may be "CreateLineItemDTO" that I build like
```
/**
 * @REST\POST("/product/{id}/line-items")
 */
public function putAction(string $id, Request $request): void
{
    $product = $productRepository->findById($id);
    $dto = new CreateLineItemDTO($product);
    // Here I would like to map the json body to the existing $dto variable.
}
```

does it make sense?

**Comment by romm** [comment]
> Also I assumed that the library couldn't create a Money because the sent type is a string, while the constructor has float (and I don't want to create a static method fromString in a core value object, just because a mapper needs it). Anyway even if I'm right, I still could use the bind for this use case as well.

The library will take care of casting a string representation of a float to a float, FYI this happens here:
https://github.com/CuyZ/Valinor/blob/e2800339411b68a24eebc266377184c76ef2701e/src/Type/Types/FloatType.php#L35-L47

> Since you are there, I have another use case that I need to deal with: sometimes I create my DTO before allowing Symfony's Form to do its magic, this is needed in cases where some of the input is contained in the url path (and not in the body), then once constructed the DTO, I instruct Symfony Form to map all the other properties using the json body.
>
> Let me give you an example to clarify: let's say we have POST /products/{productId}/line-items and I have the DTO CreateLineItemDTO that represents the input in the body request (supposedly the input to create a line item)

This is not how it would be done with this library: it is not intended — nor will it ever be — to hydrate pre-constructed objects.

For your use case, it seems like the `CreateLineItemDTO` could just be a typed property/argument somewhere in your object tree, Valinor would do the mapping automatically (combined with the `bind` trick we talked about above).

**Comment by danydev** [comment]
Just to clarify, the root problem in my case if that part of the input (the product identifier) is in the request url. And the remaining input (all the other fields) are in the json body.

So I think the best option with Valinor would be to create one single input, taking the id from the request and the other fields from the json body. It may look a bit hacky to do it in the controller, but surely it's an option.

Thanks

**Comment by romm** [comment]
Right, I misunderstood that part. Indeed the best way to do that would probably be to modify the source before giving it to the mapper — shouldn't be that hard, especially if it needs to be added at the root level.

**Comment by danydev** [comment]
I just tried it out the `bind` option. I think I could not work with this, since what I'm receiving in the callback is the entire source, forcing me to create adhoc callbacks in order to map to the correct field (i.e. I'm receiving the root source, not just the id)

ideally I would configure it like "for this field, use this bind callback", so I could receive the value of that field in the callback and the callback code could be reusable. I realize that this is not the way Valinor does things, I just want to give you an idea about my use case and expectations.

**Comment by romm** [comment]
Looks like there is an issue, the callback should not receive the whole source as argument, only the value at the concerned path. Could you show the objects you're trying to map, as well as the configuration of the mapper builder?

**Comment by romm** [comment]
Looks like a bug, probably caused by the fact that the constructor has only one argument. I'll take a look ASAP and come back to you!

**Comment by danydev** [comment]
Ok, cool. In the meanwhile, can I ask if there are ways to handle this case during the mapping?
I have cases where the DTOs that I need to map are exposed differently in the API (so in the "source"). And I can't / don't want just modify the DTO since it's a "core" DTO (i.e. that it's passed through my services where some business logic is applied, it's not just the user input).

So something like

MyDto.php
```
...
private bool $closed;
...
```

while the source may be `{"isClosed": false}`

or things like
MyInputDTO.php
```
ThirdDTO $dto;
private bool $active = false;
```

MyInputDTO.php
```
private string $description;
```

and the source looks like `{"active": true, "description": "bla"}`, so how you can imagine I should be able to map MyInputDTO::dto.description to `description` in the source. Something that as of today I do using Symfony's Form with something like
```
        $builder->add(
            'description',
            TextType::class,
            [
                'property_path' => 'dto.description',
            ]
        )
```

**Comment by romm** [comment]
Hi @danydev I've done some work in #72 to improve the way the `bind()` method works. Could you try to checkout the branch of the PR and try the code below (with maybe some adaptation) to see if that would better fit your use case?

```php
$command = (new MapperBuilder())
    ->bind(function (string $productId) use ($productRepository): Product {
        return $productRepository->findByID($productId);
    })
    ->mapper()
    ->map(
        CreateLineItemDTO::class,
        array_merge(
            ['product' => $productId],
            json_decode($request->getContent(), true)
        )
    );
```

Concerning your last message in date, @Mopolo has been working on a solution for this kind of usecases. We'll try to get back at you as soon as possible so you can give it a try (that would actually help us 🙂 ).

**Comment by romm** [comment]
Hi @danydev; @Mopolo has done wonderful work that could help with edge cases like yours. Please read the [documentation](https://github.com/CuyZ/Valinor#modifiers) for more details.

If something is still not relevant, please don't hesitate to re-open this issue or open a new one.
