### ISSUE TITLE
Problems with $cacheDir attribute

### ISSUE THREAD

**Issue by marek-mikula** [CuyZ/Valinor#65]
Hello,

I was having some problems with permissions on my temp folder on my Mac so I decided to provide my own custom cache folder for compiled files.

But I ran into an issue. The cached string is firstly put into temp folder and then 'renamed' (moved into my specified cache folder') so I can't get passed the error with my permissions.

Is there any specific reason why to do this way? Why not just directly put the cached string into the specified cache folder?

Thank you in advance and thank you for this package, it's really cool :)

https://github.com/CuyZ/Valinor/blob/e2800339411b68a24eebc266377184c76ef2701e/src/Cache/Compiled/CompiledPhpFileCache.php#L85

**Comment by romm** [comment]
Hi @marek-mikula, indeed I never ran into this issue myself but seems like some change should be done to prevent this usecase to happen.

Would you mind opening a PR with a fix that runs on your application? It looks like the test suite would not need any modification.

**Comment by marek-mikula** [comment]
Hello @romm, thank you for your immediate response. I will open PR today after work.

**Comment by romm** [comment]
That would be very much appreciated, thanks in advance!
