### ISSUE TITLE
Unexpected hydration behavior

### ISSUE THREAD

**Issue by roquie** [CuyZ/Valinor#68]
I copy-paste example and run it:

```php
$rawJson = <<<TEST
{
    "id": 1337,
    "content": "Do you like potatoes?",
    "date": "1957-07-23 13:37:42",
    "answers": [
        {
            "user": "Ella F.",
            "message": "I like potatoes",
            "date": "1957-07-31 15:28:12"
        },
        {
            "user": "Louis A.",
            "message": "And I like tomatoes",
            "date": "1957-08-13 09:05:24"
        }
    ]
}
TEST;

final class Thread
{
    public function __construct(
        public readonly int $id,
        public readonly string $content,
        public readonly DateTimeInterface $date,
        /** @var Answer[] */
        public readonly array $answers,
    ) {}
}

final class Answer
{
    public function __construct(
        public readonly string $user,
        public readonly string $message,
        public readonly DateTimeInterface $date,
    ) {}
}

$result = (new \CuyZ\Valinor\MapperBuilder())
    ->mapper()
    ->map(
        Thread::class,
        new \CuyZ\Valinor\Mapper\Source\JsonSource($rawJson)
    );
```

I got following result:
<img width="408" alt="Screenshot 2022-01-28 at 19 19 43" src="https://user-images.githubusercontent.com/3214290/151583052-80c2d56a-3b5f-437e-9a3c-c76bad37090b.png">

But I expect array of  `Answer` objects in `answers` property. What am I doing wrong?

P.S. PHP 8.1.1, library version: 0.5.0

**Comment by roquie** [comment]
Also `@var array<Answer>` or `@var Answer[]` not working in property declaration (i.e. without constructor or static methods).

**Comment by romm** [comment]
Indeed the example seems incorrect, I'll change it to something actually working.

@roquie it should be working with properties without constructor, could you post here the code that's not working?

**Comment by roquie** [comment]
> Indeed the example seems incorrect, I'll change it to something actually working.

Good :)

> @roquie it should be working with properties without constructor, could you post here the code that's not working?

Oh, sorry. Now I double checked this. It's my mistake with camelCase/snake_case notation.

By the way, how to automatically convert case from source to DTO? Maybe via Attributes or "`CustomMappingStrategy`" existing?
