### ISSUE TITLE
Require `ocramius/package-versions` instead of `composer/package-versions-deprecated`

### ISSUE THREAD

**Issue by Ocramius** [CuyZ/Valinor#7]
`composer/package-versions-deprecated` is a polyfill package designed for supporting older PHP versions: it is a replacement for `ocramius/package-versions`, but doesn't declare any of said API (owned by the parent `ocramius/package-versions` package).

It would be better, at library version, to declare a dependency on `ocramius/package-versions:^2` (which runs on `php:^7.4.7`), rather than including the polyfill itself.

**Comment by stof** [comment]
Given that `ocramius/package-versions` 2.x works only with Composer 2+, another option is to use the `composer-runtime-api` API directly.

**Comment by romm** [comment]
Thanks for the tip!
