### ISSUE TITLE
misc: change attribute arguments compilation

### ISSUE THREAD

**Issue by romm** [CuyZ/Valinor#92]
Instead of serializing all arguments, only those with an object value should be serialized: scalar values should be `var_export`'ed. 

Reference:

https://github.com/CuyZ/Valinor/blob/e3592e18c5c6cdab104b6bfd38d0223723ccc08a/src/Definition/Repository/Cache/Compiler/AttributesCompiler.php#L94-L99

Should look like:

https://github.com/CuyZ/Valinor/blob/fdef93074c32cf36072446da8a3466a1bf781dbb/src/Definition/Repository/Cache/Compiler/ParameterDefinitionCompiler.php#L45-L52

**Comment by kang8** [comment]
`$arguments` cannot be scalar.

https://github.com/CuyZ/Valinor/blob/58d54013716dc67ac27fe2117f481de496c1b148/src/Definition/Repository/Cache/Compiler/AttributesCompiler.php#L41

[ReflectionAttribute::getArguments()](https://www.php.net/manual/en/reflectionattribute.getarguments.php#refsect1-reflectionattribute.getarguments-returnvalues) return array, array is not scalar.
